language: go
go:
  - 1.2
  - release
  - tip
branches:
  only:
    - master
install:
  - cd; mkdir gopkg; export GOPATH=$HOME/gopkg
  - go get -tags nogui github.com/agl/pond/client
#  - go get -tags ubuntu github.com/agl/pond/client
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq golang git libgtk-3-dev libgtkspell-3-dev libtspi-dev trousers tor mercurial pkg-config
#script: go test
