language: go
go:
  - 1.2
  - release
  - tip
branches:
  only:
    - master
install:
  - cd; mkdir gopkg; export GOPATH=$HOME/gopkg
# This is for the CLI interface - we want to build it
  - go get -tags nogui github.com/agl/pond/client
# Someday, we want to build the GTK stuff and the following tag should do it
  - go get -tags ubuntu github.com/agl/pond/client
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq golang git libgtk-3-dev libgtkspell-3-dev libtspi-dev trousers tor mercurial pkg-config libgtkspell-3-0 libgtkspell0
script:
  - go build -tags nogui github.com/agl/pond/client
  - go build -tags ubuntu github.com/agl/pond/client
