language: go
go:
  - 1.2
  - release
  - tip
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq golang git libgtk-3-dev libgtkspell-3-dev libtspi-dev trousers tor mercurial
script: go test
